name: Deploy Azure App Service
on:
  workflow_call:
    inputs: 
      artifact_name:
        description: 'Set the artifact name'
        required: true
        type: string
      target_app_name:
        description: 'Set the target App Name'
        required: true
        type: string
    secrets:
      target_publish_profile:
        required: true
      subscription_id:
        description: 'Azure Subscription ID'
        required: true
      azure_client_id:
        description: 'Azure client ID'
        required: true
      azure_tenant_id:
        description: 'Azure tenant ID'
        required: true
permissions:
  # to Fetch an OpenID Connect (OIDC) token
  id-token: write
  contents: read
  
jobs:
  deploy-app-service:
    runs-on: ubuntu-latest
    steps:
    - name: Print secret
      run: |
        echo "The secret is successfully subscription_id"
        echo "The value of the secret is: ${{ secrets.target_publish_profile }}"
    - name: Print secret
      run: |
        echo "The secret is successfully azure_client_id"
        echo "The value of the secret is: ${{ secrets.azure_client_id }}"
    - name: Print secret
      run: |
        echo "The secret is successfully azure_tenant_id"
        echo "The value of the secret is: ${{ secrets.azure_tenant_id }}"
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        subscription-id: '6c8cd46b-6887-4cba-8596-a38ceeabd610'
        client-id: '921afbfe-b2c3-4d0b-b2eb-ec131101e2d1'
        tenant-id: 'f4acf4b0-d8ce-47de-9567-63bdeee62d4e'
        
    - name: Azure Web App Deploy
      uses: azure/webapps-deploy@v2
      with:
        # Name of the App Service
        app-name: ${{ inputs.APP_NAME }}
        publish-profile: ${{ secrets.target_publish_profile }}
