name: Deploy Azure App Service
on:
  workflow_call:
    inputs: 
      artifact_name:
        description: 'Set the artifact name'
        required: true
        type: string
      target_app_name:
        description: 'Set the target App Name'
        required: true
        type: string
    secrets:
      target_publish_profile:
        required: true
      subscription_id:
        description: 'Azure Subscription ID'
        required: true
      azure_client_id:
        description: 'Azure client ID'
        required: true
      azure_tenant_id:
        description: 'Azure tenant ID'
        required: true

jobs:
  deploy-app-service:
    runs-on: ubuntu-latest
    steps:
    - name: Print secret
      run: |
        echo "The secret is successfully subscription_id"
        echo "The value of the secret is: ${{ secrets.subscription_id }}"
    - name: Print secret
      run: |
        echo "The secret is successfully azure_client_id"
        echo "The value of the secret is: ${{ secrets.azure_client_id }}"
    - name: Print secret
      run: |
        echo "The secret is successfully azure_tenant_id"
        echo "The value of the secret is: ${{ secrets.azure_tenant_id }}"
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        subscription-id: ${{ secrets.subscription_id }}
        client-id: ${{ secrets.azure_client_id }}
        tenant-id: ${{ secrets.azure_tenant_id }}
        enable-AzPSSession: true
        
    - name: Azure Web App Deploy
      uses: azure/webapps-deploy@v2
      with:
        # Name of the App Service
        app-name: ${{ inputs.APP_NAME }}
        publish-profile: ${{ secrets.target_publish_profile }}
