name: Deploy Azure App Service
on:
  workflow_call:
    inputs:
      target_environment:
        description: 'Set the target environment to fetch the corresponding Azure Service Principal details'
        # no default value set to ensure target environment is supplied to get the Azure Service Principal details for the corresponding environment 
        required: true
        type: string    
      artifact_name:
        description: 'Set the artifact name'
        required: true
        type: string
      target_app_name:
        description: 'Set the target App Name'
        required: true
        type: string
    secrets:
      target_publish_profile:
        required: true

jobs:
  deploy-app-service:
    environment: ${{ inputs.target_environment }}
    runs-on: "${{ inputs.target_runner }}"
    steps:

    - name: Download Artifact - ${{ inputs.artifact_name }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}


    - name: Azure Web App Deploy
      uses: azure/webapps-deploy@v2
      with:
        # Name of the App Service
        app-name: ${{ inputs.APP_NAME }}
        publish-profile: ${{ inputs.target_publish_profile }}
