name: Test Print Param

on:
  workflow_call:
    inputs:
      fname:
        description: 'Set the artifact first name'
        required: true
        type: string
      path:
        description: 'Set the artifact path name'
        required: true
        type: string

jobs:

  test-run-print:
    runs-on: ubuntu-latest
    steps:
    - name: Echo secret
      run: |
            echo "This is a secret: ${{ inputs.fname }}"

      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.
