name: Test Print Param

on:
  workflow_call:
    inputs:
      fname:
        description: 'Set the artifact first name'
        required: true
        type: string
      path:
        description: 'Set the artifact path name'
        required: true
        type: string

jobs:
  test-run-print:
    runs-on: ubuntu-latest
    steps:
    - name: Echo fname
      run: |
            echo "This is a fname value: ${{ inputs.fname }}"
    - name: Generate APP_NAME
      run: |
        ls -alFh
        VARS_JSON='${{ toJson(vars) }}'
        APP_NAME=$(echo "$VARS_JSON" | jq -r ".${{ inputs.fname }}")
        echo "::notice::APP_NAME=$APP_NAME"
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
    - name: echo fname again
      run: |
            echo "This is a fname value: ${{ env.APP_NAME }}"
